plugins:
  replace-foo-with:
    path: ./tests/fixtures/tree-sitter-lint-plugin-replace-foo-with
rules:
  no-default-default:
    level: error
  prefer-impl-param:
    level: error
  no-lazy-static:
    level: error
  replace-foo-with/replace-foo-with-bar:
    level: error
  replace-foo-with/replace-foo-with-something:
    level: error
    options: whee
  replace-foo-with/starts-with-use:
    level: error
  require-blazing-keyword:
    level: error
